### ISSUE TITLE
Improper sleep label

### ISSUE THREAD

**Issue by nwg-piotr** [jovanlanik/gtklock-powerbar-module#1]
Hi,

Good update, thank you!

One possible issue: is it all right with the suspend label? I'm seeing something like this:

![image](https://user-images.githubusercontent.com/20579136/197298749-34234110-f710-46e6-95d3-f588697fd080.png)

[edit] Also: could I opt-out from using the suspend button? The `systemctl suspend` command doesn't work well on my system.

**Comment by jovanlanik** [comment]
Set --suspend-command to an empty string to disable the button. As for the label, thank you for pointing out the mistake.

**Comment by nwg-piotr** [comment]
Very well, thanks. I'll add a corresponding field to nwg-shell-config.

**Comment by jovanlanik** [comment]
I'll push out a release with the fix.

**Comment by nwg-piotr** [comment]
Great. It means a minor shell update coming soon. :)
