### ISSUE TITLE
Require authentication for poweroff and restarts

### ISSUE THREAD

**Issue by WasteOfO2** [jovanlanik/gtklock-powerbar-module#2]
A malicious actor can directly power cycle the system without the owner's permission. If the user has unsaved work or is in the middle of something, this can potentially lead to data loss and corruption of the said work. Windows and Macs handle this differently by waiting for the processes to end rather than killing the processes outright as Linux does.

Remedies for the said issue could be:

1. Not using this module
2. Only permit user to power cycle (password authentication)
3. Warn user regarding potential data loss if said work is not saved or backed up (a confirmation prompt) in case this was triggered accidentally

Thank you for this great program :3

**Comment by bhepple** [comment]
As a workaround, you can disable those buttons with:
```
gtklock <other options> --reboot-command="" --poweroff-command=""
```
